#!/bin/bash
#
# @date   : 2019-10-21 (SOL 320)
# @author : Greg Sainton, IPGP

# Simple shell script to convert UTC Date to LMST date
# Based on the program utc2lmst executed in Python

# MARSCONVERTER_SCRIPTS environement variable must be set
# in your bash (or whatever shell you are using) first. 
# This variable must be the directory
# where to find utc2lmst, utc2lmst.py and the python class
# MarsTimeConverter in the file marstimeconverter.py


#abort on error
set -e

function usage
{
    echo "usage: utc2lmst -d UTCDate "
    echo "   ";
    echo "  -d | --date              : UTC format date";
    echo "  -h | --help              : This message";
}

function parse_args
{
  # positional args
  args=()

  # named args

   case "$1" in
       -d | --date )                 date="$2";               shift;;
       -h | --help )                 usage;                   exit;; # quit and show usage
       * )                           args+=("$1")             # if no match, add it to the positional args
   esac

  # restore positional args
  set -- "${args[@]}"


  # validate required args
  if [[ -z "${date}" ]]; then
      echo "Invalid arguments"
      usage
      exit;
  fi

}

function run
{
  parse_args "$@"
  if [ -z "${MARSCONVERTER_SCRIPTS}" ]; then echo "MARSCONVERTER_SCRIPTS is unset"; else python "$MARSCONVERTER_SCRIPTS/marstimeconverter/cli/utc2lmst.py" -d $date; fi
}

run "$@";
